version: "3.0"
services:

  redis:
    container_name: my_redis
    image: redis
    env_file:
      - ./config/redis.conf

  db:
    container_name: my_db
    image: mysql
    env_file:
      - ./config/db.conf
    ports:
      - 8000:3306
    depends_on: 
      - redis

  flask:
    container_name: web_app_sc
    restart: always
    build:
      context: ./services/app
      dockerfile: Dockerfile
    env_file:
      - ./config/python.conf
    expose:
      - "8000"
      - "5000"
      - "3031" 
    ports:
      - "1080:5000"
    depends_on:
      - db
    tty: true

  server:
    container_name: nginx
    restart: always
    build: ./services/server
#    volumes:
#      - ./services/server/html:/usr/share/nginx/html
    ports:
      - "8080:80"
    

networks:
  default:
    driver: bridge